********************************
* Ember Knight                 *
* Linker File                  *
*    Nick Waun                 *
*    02-21-2017                *
********************************

 DSK /EK/BIN/EMBERK.LNK
 STR "/EK/BIN/MAIN.L",00
 STR "/EK/BIN/GRTABLES.L",00
 STR "/EK/BIN/LORES.L",00
 STR "/EK/BIN/HGR.L",00
 STR "/EK/BIN/FONT.L",00
 STR "/EK/BIN/GRAPHIX.L",00
 STR "/EK/BIN/TXTSPL.L",00
 STR "/EK/BIN/MATH.L",00
 STR "/EK/BIN/RAND.L",00
 STR "/EK/BIN/UTIL.L",00
 STR "/EK/BIN/DISKIO.L",00
 STR "/EK/BIN/TITLSCRN.L",00
 BRK
