********************************
* Apple 2 TANKS                *
* Linker File                  *
*    Nick Waun                 *
*    05-02-2017                *
********************************

 DSK /TKS/BIN/TANKS.LNK
 STR "/TKS/BIN/MAIN.L",00
 STR "/TKS/BIN/GRTABLES.L",00
 STR "/TKS/BIN/LORES.L",00
 STR "/TKS/BIN/HGR.L",00
 STR "/TKS/BIN/FONT.L",00
 STR "/TKS/BIN/GRAPHIX.L",00
 STR "/TKS/BIN/TXTSPL.L",00
 STR "/TKS/BIN/MATH.L",00
 STR "/TKS/BIN/RAND.L",00
 STR "/TKS/BIN/UTIL.L",00
 STR "/TKS/BIN/DISKIO.L",00
 STR "/TKS/BIN/TITLSCRN.L",00
 BRK
